#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "QI, Weimin"
# Short bio or description (displayed in the header)
description: "I am now a doctoral candidate in the Chinese University of Hong Kong (Shenzhen), enrolled in 2019, with a five-year academic duration. I belong to the Master-Doctor program of Computer and Information Engineering, and my research here is mainly focused on the safe navigation of sailing robots. Before that, I got my bachelor's degree from Central South University."

#
# Flags below are optional
#

# URL of your avatar or profile pic (you could use your GitHub profile pic)

avatar: https://raw.githubusercontent.com/WeiminQi/WeiminQi.github.io/master/images/name.png
# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://raw.githubusercontent.com/WeiminQi/WeiminQi.github.io/master/images/origin.png

# Tabs in header. There are 'Home', 'Education', 'Research', 'Award'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: Recent Projects
    url: /projects
  - name: Research
    url: /research
  - name: Services
    url: /services
  - name: Awards
    url: /award
  - name: Resume
    url: /resume

# Pagination
paginate: 10000

excerpt_separator: <!-- more -->

# Includes an icon in the footer for each username you enter
footer-links:
  behance: 
  dribbble:
  zhihu: 
  email: 
  facebook:
  flickr:
  github: 
  googleplus: 
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  #twitter: frommidworld
  youtube:

# Text under the icons in footer
footer-text: Copyright 2023 Weimin Qi. Powered by <a href="https://www.jekyll.com.cn/">Jekyll</a> , <a href="https://fromendworld.github.io/LOFFER/document/">LOFFER</a> and <a href="https://lemonchann.github.io/blog/">Lemon's blog</a>. Hosted by <a href="https://pages.github.com/">GitHub Pages</a>.



permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

